name: Merge PR to Base

on:
  repository_dispatch:
    types: [edit_linked_issues_field]

env:
  issueKeys: ${{ github.event.client_payload.issueKeys }}
  JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
  JIRA_API_TOKEN: ${{ secrets.JIRA_BASIC_API_TOKEN }}

jobs:
  edit-fields:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change linkedIssues fields in Jira
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueKeys = process.env.issueKeys;
            console.log(issueKeys);
            
