name: Merge PR to Base

on:
  repository_dispatch:
    types: [edit_linked_issues_field]

env:
  issueKeys: ${{ github.event.client_payload.issueKeys }}
  JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
  JIRA_API_TOKEN: ${{ secrets.JIRA_BASIC_API_TOKEN }}

jobs:
  edit-fields:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change linkedIssues fields in Jira
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueKeys = process.env.issueKeys;
            const keysArr = issueKeys.split(',');
            keysArr.map((ele) =>{
              console.log(ele);
              var myHeaders = new Headers();
              myHeaders.append("Content-Type", "application/json");
              myHeaders.append("Authorization", "Basic Ymh1dmFuYmh1dmlzbUBnbWFpbC5jb206QVRBVFQzeEZmR0YwXzl0T1NhS1dkS3FYZFpNNUtkblhETU5FeUNlVUhjRnllbVhXaWkteVVOZUxqenMtM2hGREpERnlGc1VDdjVYNF80VldIbmdQckhJdWRER2pVYmxsdWNwc2FrVjQ1ZUgxS0ROSFdiZEtfaGpZbXpLeVlhNXNuVkt2S0NlWUJYdzRlYjlKWEF5SkRZNU5WRWxfaWNoRnJIMDhmRFRpSVNWNVlEN3ZYSXVfTVJzPTA1RDU3NkM2");
              myHeaders.append("Cookie", "atlassian.xsrf.token=27301f94-52ef-472c-92bd-8fc0e3b64628_1d74c5f029ad70ad516de0138ba3c8d7640a498b_lin");

              var raw = JSON.stringify({
                "fields": {
                  "customfield_10038": "SubTask_WithParentBranch"
                }
              });

              var requestOptions = {
                method: 'PUT',
                headers: myHeaders,
                body: raw,
                redirect: 'follow'
              };
              
              var url = process.env.JIRA_BASE_URL+ele;

              fetch(process., requestOptions)
                .then(response => response.text())
                .then(result => console.log(result))
                .catch(error => console.log('error', error));
              });
            console.log(issueKeys);
            
