name: Update Jira Custom Field

on:
  pull_request_review:
    types:
      - submitted
jobs:
  update-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Retrieve Branch Name
        id: branch-name
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          BRANCH_NAME=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
            | jq -r '.head.ref')
          echo "Branch Name: $BRANCH_NAME"
          IFS='-' read -ra SPLIT_ARRAY <<< "$BRANCH_NAME"
          echo "First Part: ${SPLIT_ARRAY[0]}"
          echo "Second Part: ${SPLIT_ARRAY[1]}"
          echo "Third Part: ${SPLIT_ARRAY[2]}"
          FIRST_PART=$(echo "$BRANCH_NAME" | awk -F, '{print $1}')
          echo "First Part: $FIRST_PART"
          ISSUE_KEY = "${SPLIT_ARRAY[0]}${{ env.STRING2 }}"

      - name: Update Jira Custom Field
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_BASIC_API_TOKEN }}
        run: |
          echo "PR Body: ${{ github.event.pull_request.body }}"
          ISSUE_KEY="JGI-11"  # Replace with the Jira issue key
          API_ENDPOINT="/rest/api/2/issue/$ISSUE_KEY"  # Replace with the desired Jira API endpoint

          # Define your request body JSON
          REQUEST_BODY='{
            "fields": {
              "customfield_10038": "True"
            }
          }'

          # Make the API call to Jira
          curl --location --request PUT $JIRA_BASE_URL$API_ENDPOINT \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $JIRA_API_TOKEN" \
            -d "$REQUEST_BODY"
