name: Update Jira Custom Field

on:
  pull_request_review:
    types:
      - submitted
    
jobs:
  update-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Update Jira Custom Field
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        run: |
          ISSUE_KEY="JGI-11" # Replace with the Jira issue key you want to update
          CUSTOM_FIELD_ID="customfield_10038" # Replace with the ID of the custom field you want to update
          CUSTOM_FIELD_VALUE="True" # Replace with the new value you want to set

          curl -D- -u $JIRA_USERNAME:$JIRA_API_TOKEN -X PUT \
            -H "Content-Type: application/json" \
            -d "{ \"fields\": { \"$CUSTOM_FIELD_ID\": \"$CUSTOM_FIELD_VALUE\" } }" \
            $JIRA_BASE_URL/rest/api/2/issue/$ISSUE_KEY

