name: Update Jira Custom Field

on:
  pull_request_review:
    types:
      - submitted
    
jobs:
  update-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Update Jira Custom Field
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_BASIC_API_TOKEN: ${{ secrets.JIRA_BASIC_API_TOKEN  }}
        run: |
          curl --location --request PUT 'https://$JIRA_BASE_URL/rest/api/2/issue/JGI-11' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Basic $JIRA_BASIC_API_TOKEN' \
          --data '{
              "fields": {
                  "customfield_10038": "True"
              }
          }'

